### ISSUE TITLE
Game crashes without any plugins when I enter game menu

### ISSUE THREAD

**Issue by Zydnar** [austinvaness/PluginLoader#3]
This is error trace I get when entering game menu:

```
Exception occured: System.MissingMethodException: Method not found: 'Void Sandbox.Graphics.GUI.MyGuiControlButton..ctor(System.Nullable`1<VRageMath.Vector2>, VRage.Game.MyGuiControlButtonStyleEnum, System.Nullable`1<VRageMath.Vector2>, System.Nullable`1<VRageMath.Vector4>, VRage.Utils.MyGuiDrawAlignEnum, System.String, System.Text.StringBuilder, Single, VRage.Utils.MyGuiDrawAlignEnum, Sandbox.Graphics.GUI.MyGuiControlHighlightType, System.Action`1<Sandbox.Graphics.GUI.MyGuiControlButton>, VRage.Audio.GuiSounds, Single, System.Nullable`1<Int32>, Boolean, Boolean, Boolean, System.Action`1<Sandbox.Graphics.GUI.MyGuiControlButton>)'.
   at avaness.PluginLoader.Patch.Patch_CreateMainMenu.Postfix(MyGuiScreenMainMenu __instance, Vector2 leftButtonPositionOrigin, Vector2& lastButtonPosition)
   at DMD<DMD<CreateMainMenu_Patch1>?36052245::CreateMainMenu_Patch1>(MyGuiScreenMainMenu this, Vector2 leftButtonPositionOrigin, Vector2& lastButtonPosition)
   at SpaceEngineers.Game.GUI.MyGuiScreenMainMenu.RecreateControls(Boolean constructor)
   at Sandbox.Graphics.GUI.MyScreenManager.AddScreens()
   at Sandbox.Graphics.GUI.MyScreenManager.Update(Int32 totalTimeInMS)
   at Sandbox.Graphics.GUI.MyDX9Gui.Update(Int32 totalTimeInMS)
   at Sandbox.Graphics.GUI.MyGuiSandbox.Update(Int32 totalTimeInMS)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
```

**Comment by austinvaness** [comment]
Please post the whole game log if you can.

**Comment by Zydnar** [comment]
When I compiled it by myself it worked perfectly fine - maybe version mismatch.
